name: RPM Build and Upload

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Set Version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

    - name: Run Docker Container
      run: docker run --privileged -d --name builder --network host rockylinux:9 /bin/sleep infinity 

    - name: Install build tools RPM
      run: |
        docker cp ./ builder:/build
        docker exec builder bash -c "yum install -y epel-release && yum install -y make git mock"
        docker exec builder bash -c "rm -rf /etc/mock/default.cfg"
    - name: "Setup SDK"
      run: |
        docker exec builder bash -c "ln -s /build/sdk9.cfg /etc/mock/default.cfg"
        docker exec builder bash -c "ls -l /build/sdk9.cfg /etc/mock/default.cfg"
    
    - name: Install RPM
       run: |
        docker exec builder bash -c "git config --global --add safe.directory /build"
        docker exec builder bash -c "cd /build/ && VERSION=${VERSION} make rpm"

      env:
        VERSION: 0.0.1
