name: RPM Build and Upload

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Install mock
      run: |
        sudo apt-get install -y epel-release
        sudo apt-get update
        sudo apt-get install -y mock

    - name: Set Version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

    - name: Make RPM
      run: make rpm
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
