name: RPM Build and Upload

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Set Version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

    - name: Run Docker Container
      run: docker run --privileged -d --name builder rockylinux:9 /bin/sleep infinity 

    - name: Build RPM
      run: |
        docker cp ./ builder:/build
        docker exec builder bash -c "yum install -y epel-release && yum install -y make git mock"
        docker exec builder bash -c "git config --global --add safe.directory /build"
        docker exec builder bash -c "cd /build/ && make rpm"
        docker exec builder git -C /build/ checkout ${GITHUB_SHA}
      env:
        VERSION: 0.0.1
