name: Cargo Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:

  build_and_test:
    name: logstatter - latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@latest

      - name: Set up Rust
        run: |
          if ($env:GITHUB_JOB_OS -eq "windows-latest") {
            choco install rust
          } else {
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          }
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build and test
        run: cargo build --verbose
