name: Linux Build and Release

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release_x86_64:
    name: logstatter - latest - x86_64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build and test
        run: cargo build --release

      - name: Create tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: git fetch --all --tags && tag_name="latest/linux/x86_64" && if ! git rev-parse -q --verify "refs/tags/$tag_name" >/dev/null; then git tag "$tag_name" && git push origin "$tag_name"; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create x86_64 Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/logstatter
          tag_name: latest/linux/x86_64

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: latest/linux/x86_64

  build_and_release_aarch64:
    name: logstatter - latest - aarch64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
        arch:
          - aarch64

    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build and test
        run: cargo build --release

      - name: Create tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: git fetch --all --tags && tag_name="latest/linux/aarch64" && if ! git rev-parse -q --verify "refs/tags/$tag_name" >/dev/null; then git tag "$tag_name" && git push origin "$tag_name"; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create aarch64 Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/logstatter
          tag_name: latest/linux/aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: latest/linux/aarch64
