name: Windows Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:

  build_and_test:
    name: logstatter - latest
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        run: choco install rust -y
      - name: Build and test
        run: cargo build --verbose
